name: Sync from Hostinger FTP

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Fetch files via FTP
        run: |
          lftp -c "open -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} ${{ secrets.FTP_HOST }};\
          mirror --delete --verbose ${{ secrets.FTP_PATH }} ./"

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-sync: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push

